import { jsPDF } from 'jspdf';
import { DietPlanFull, HealthMetrics } from '../types';

export const generatePDF = (plan: DietPlanFull, metrics: HealthMetrics, patientName: string) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(16, 185, 129); // Emerald Green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("AI-NutriCare Diet Plan", 15, 20);
  
  doc.setFontSize(12);
  doc.text(`Patient: ${patientName}`, 15, 30);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 30);

  // Health Summary
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Health Summary", 15, 55);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Glucose: ${metrics.glucose} mg/dL`, 15, 65);
  doc.text(`Cholesterol: ${metrics.cholesterol} mg/dL`, 65, 65);
  doc.text(`BMI: ${metrics.bmi}`, 115, 65);
  doc.text(`BP: ${metrics.bloodPressure} mm Hg`, 165, 65);

  // Guidelines
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Key Guidelines", 15, 80);
  
  doc.setFontSize(11);
  let yPos = 90;
  plan.recommendations.forEach((rec) => {
    doc.text(`• ${rec}`, 15, yPos);
    yPos += 8;
  });

  // Diet Plan
  yPos += 10;
  doc.setFontSize(16);
  doc.text("Weekly Meal Plan", 15, yPos);
  
  yPos += 10;
  
  plan.weeklyPlan.forEach((day) => {
    // Check page break
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFillColor(240, 240, 240);
    doc.rect(15, yPos - 6, 180, 8, 'F');
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(day.day, 18, yPos);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    yPos += 10;
    
    const meals = [
      { type: "Breakfast", item: day.breakfast },
      { type: "Lunch", item: day.lunch },
      { type: "Snack", item: day.snack },
      { type: "Dinner", item: day.dinner }
    ];

    meals.forEach((m) => {
        doc.text(`${m.type}: ${m.item.name} (${m.item.calories} kcal)`, 20, yPos);
        yPos += 7;
    });
    
    yPos += 5;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by AI-NutriCare System. Consult a doctor before starting any new diet.", 105, 290, { align: "center" });

  doc.save(`${patientName.replace(" ", "_")}_DietPlan.pdf`);
};