import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import "../App.css";

export default function Terms() {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="landing-wrapper" style={{ overflowX: 'hidden' }}>
      <nav className="navbar">
        <div className="nav-container">
          <Link to="/" className="logo" style={{ textDecoration: 'none' }}>AI-<span>NutriCare</span></Link>
          <div className="nav-menu" style={{ display: 'flex', gap: '15px' }}>
             <Link to="/" className="clay-btn-secondary" style={{ textDecoration: 'none', padding: '8px 20px' }}>← Home</Link>
          </div>
        </div>
      </nav>

      <div className="main-container" style={{ padding: '160px 24px 80px', position: 'relative' }}>
         <div style={{
          content: '""', position: 'absolute', width: '600px', height: '600px', borderRadius: '50%', filter: 'blur(120px)', zIndex: -1, background: 'rgba(124, 58, 237, 0.15)', top: '-100px', right: '-100px'
        }} />

        <div className="section-header-centered fade-in" style={{ marginBottom: '60px' }}>
          <div className="status-badge slide-up-stagger-1">⚖️ Legal Notice</div>
          <h2 className="section-title slide-up-stagger-2">Terms of <span className="purple-text" style={{ background: 'rgba(124,58,237,0.05)', padding: '0 10px', borderRadius: '12px' }}>Service</span></h2>
          <p className="section-subtitle slide-up-stagger-3">Agreement regarding the use of AI-NutriCare applications and APIs.</p>
        </div>

        <div className="bento-card slide-up-stagger-4" style={{ textAlign: 'left', margin: '0 auto', maxWidth: '800px', padding: '60px', userSelect: 'auto', WebkitUserSelect: 'auto' }}>
            <h3 style={{ fontSize: '1.4rem', marginBottom: '20px', color: 'var(--deep-slate)', fontFamily: 'Outfit, sans-serif' }}>1. Not Medical Advice</h3>
             <p style={{ marginBottom: '20px', lineHeight: '1.8' }}>The analysis, diet recommendations, and therapeutic protocol outputs generated by AI-NutriCare are for informational and educational purposes only. This service is not formally FDA-approved software and does not constitute absolute medical diagnosis or treatment. Always consult a licensed healthcare provider before adopting new supplement regimens.</p>

             <h3 style={{ fontSize: '1.4rem', marginBottom: '20px', color: 'var(--deep-slate)', fontFamily: 'Outfit, sans-serif' }}>2. Acceptable Use</h3>
             <p style={{ marginBottom: '20px', lineHeight: '1.8' }}>You agree not to reverse engineer the AI analysis pipelines, attempt to exploit API endpoints to extract generalized training data, or submit falsified medical documents designed to test or manipulate algorithmic constraints.</p>

             <h3 style={{ fontSize: '1.4rem', marginBottom: '20px', color: 'var(--deep-slate)', fontFamily: 'Outfit, sans-serif' }}>3. Account Termination</h3>
             <p style={{ marginBottom: '0px', lineHeight: '1.8' }}>We reserve the right to suspend or terminate accounts that violate these terms, including instances of programmatic abuse (DDoS, automated scraping) or the submission of maliciously crafted payloads.</p>
        </div>
      </div>
    </div>
  );
}
